'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  TriangleAlert,
  MessageSquareText,
  Video,
  Check,
  X,
  ShieldCheck,
} from 'lucide-react'
import { cn } from '@/lib/utils'

type Resolution = 'pending' | 'confirmed' | 'dismissed'

export function ContradictionAlert() {
  const [resolution, setResolution] = useState<Resolution>('pending')

  const resolved = resolution !== 'pending'
  const confirmed = resolution === 'confirmed'

  return (
    <div
      className={cn(
<<<<<<< HEAD
        'relative overflow-hidden rounded-xl border p-5 transition-colors',
=======
        'animate-pop relative overflow-hidden rounded-xl border p-5 transition-all duration-300',
>>>>>>> origin/main
        confirmed
          ? 'border-danger/40 bg-danger/[0.06]'
          : resolution === 'dismissed'
            ? 'border-border bg-card/60'
            : 'border-warning/40 bg-warning/[0.06]',
      )}
    >
      {/* accent bar */}
      <span
        className={cn(
          'absolute inset-y-0 left-0 w-1',
          confirmed
            ? 'bg-danger'
            : resolution === 'dismissed'
              ? 'bg-muted-foreground/40'
              : 'bg-warning',
        )}
      />

      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div
            className={cn(
              'flex size-9 items-center justify-center rounded-lg',
              confirmed
                ? 'bg-danger/15 text-danger'
                : resolution === 'dismissed'
                  ? 'bg-secondary text-muted-foreground'
                  : 'bg-warning/15 text-warning',
            )}
          >
            <TriangleAlert className="size-5" />
          </div>
          <div>
            <h2 className="text-base font-semibold text-foreground">
              Possible Contradiction Detected
            </h2>
            <p className="mt-0.5 text-xs text-muted-foreground">
              Flag CF-07 · generated by AI analysis layer · requires human
              review
            </p>
          </div>
        </div>
        <div className="hidden items-center gap-2 sm:flex">
          <span className="rounded-md border border-danger/30 bg-danger/12 px-2 py-1 font-mono text-[10px] font-semibold tracking-wide text-danger uppercase">
            Severity · High
          </span>
          <span className="rounded-md border border-border bg-secondary px-2 py-1 font-mono text-[10px] font-semibold tracking-wide text-muted-foreground uppercase">
            Confidence · 91%
          </span>
        </div>
      </div>

      {/* Evidence comparison */}
      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <div className="rounded-lg border border-border bg-card/60 p-3.5">
          <p className="flex items-center gap-1.5 font-mono text-[11px] tracking-wide text-muted-foreground uppercase">
            <MessageSquareText className="size-3.5" />
            Witness statement · WS-201
          </p>
          <p className="mt-2 text-sm text-foreground">
            “Suspect left the location at{' '}
            <span className="font-semibold text-warning">9:00 PM</span>.”
          </p>
        </div>
        <div className="rounded-lg border border-border bg-card/60 p-3.5">
          <p className="flex items-center gap-1.5 font-mono text-[11px] tracking-wide text-muted-foreground uppercase">
            <Video className="size-3.5" />
            CCTV evidence · Camera RVS-04
          </p>
          <p className="mt-2 text-sm text-foreground">
            “Subject appears at the location at{' '}
            <span className="font-semibold text-warning">9:25 PM</span>.”
          </p>
        </div>
      </div>

      <p className="mt-3 text-[13px] leading-relaxed text-muted-foreground">
        <span className="font-medium text-foreground">Explanation: </span>
        The reported departure time conflicts with CCTV evidence — a 25-minute
        discrepancy places the subject at the scene after the stated departure.
      </p>

      {/* Actions / resolution */}
      {!resolved ? (
        <div className="mt-4 flex flex-wrap items-center gap-2.5">
          <Button
            onClick={() => setResolution('confirmed')}
            size="lg"
            className="bg-danger text-danger-foreground hover:bg-danger/90"
          >
            <Check className="size-4" />
            Confirm contradiction
          </Button>
          <Button
            onClick={() => setResolution('dismissed')}
            variant="outline"
            size="lg"
          >
            <X className="size-4" />
            Dismiss as non-issue
          </Button>
          <p className="ml-auto hidden text-[11px] text-muted-foreground md:block">
            Officer decision will be recorded to the audit trail.
          </p>
        </div>
      ) : (
        <div
          className={cn(
            'mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3.5',
            confirmed
              ? 'border-danger/30 bg-danger/10'
              : 'border-border bg-secondary/50',
          )}
        >
          <div className="flex items-center gap-2.5">
            <div
              className={cn(
                'flex size-8 items-center justify-center rounded-full',
                confirmed
                  ? 'bg-danger/20 text-danger'
                  : 'bg-muted-foreground/15 text-muted-foreground',
              )}
            >
              {confirmed ? (
                <Check className="size-4" />
              ) : (
                <X className="size-4" />
              )}
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">
                {confirmed
                  ? 'Confirmed by Officer'
                  : 'Dismissed by Officer'}
              </p>
              <p className="flex items-center gap-1.5 font-mono text-[11px] text-muted-foreground">
                <ShieldCheck className="size-3 text-success" />
                Response logged to audit trail · {caseTime()} · Det. A. Mreyen
              </p>
            </div>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setResolution('pending')}
          >
            Undo
          </Button>
        </div>
      )}
    </div>
  )
}

function caseTime() {
  return new Date().toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
  })
}
